---
- name: Start local development
  hosts: local_machine_provisioning
  remote_user: root
  vars:
    AWS_PROFILE: nc_dev-developer
    AWS_REGION: us-east-1
  vars_files:
    - ../../vars/user_config.yaml
  tasks:
    - name: Cleanup in ~/.zprofile
      copy:
        src: ./resources/zprofile_copy
        dest: ~/.zprofile
        force: true
    - name: Remove previous Anvil cache. Sometimes that's the reason of errors.
      shell:
        cmd: rm -rf ~/.anvil
    - name: Obtain token and store it in the local file
      shell:
        cmd: echo $(aws codeartifact get-authorization-token --domain n-central --domain-owner 362695845571 --region us-east-1 --query authorizationToken --output text) > ~/.__anvil_token
    - name: Populate token to the .zprofile (ZSH must be in place)
      shell:
        cmd: echo "export CODEARTIFACT_AUTH_TOKEN=$(cat ~/.__anvil_token)" >> ~/.zprofile
    - name: Populate token to the environment
      shell:
        cmd: source ~/.zprofile
    - name: Launch IDE
      shell: ~/idea-launcher
