---
- name: Enable MSP SSO flag
  hosts: remote_vra
  become: yes
  become_user: root
  tasks:
    - name: Execute refresh command
      shell:
        chdir: /home/nable/
        cmd: /opt/nable/usr/sbin/runNCLI.sh refreshldclient false true
    - name: Enable MSP SSO flag in config file
      shell:
        chdir: /home/nable/
        cmd: sed -i 's/"msp_sso":false/"msp_sso":true/g' flag_default.json
