---
- name: Update local SSH configuration
  hosts: local_machine_provisioning
  remote_user: root
  become: yes
  become_user: root
  tasks:
          - name: Ensure SSH configuration is in desired state
            copy:
              src: "{{source}}/playbooks/local_ssh/resources/ssh_config"
              dest: /private/etc/ssh/ssh_config
              owner: root
              group: wheel
              mode: '0644'
              backup: yes
# TODO: add additional file manipulation
